spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: developer
    password: passwordhere
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
